name: letterboxd
channels:
  - defaults
dependencies:
  - ca-certificates=2024.12.31
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.8.20
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.6.4
  - zlib=1.2.13
